# Generated by Django 4.0.6 on 2022-07-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='author',
            new_name='user_id',
        ),
    ]
