# Generated by Django 4.0.6 on 2022-07-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0002_rename_author_shorturl_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='full_url',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
